Repository sennight-ios/sennight-swift, pull requests merged in 2024-07, with the labels that each got.

#24 Add navigation to SwiftUI skeleton project
  Sennight/Sennight.xcodeproj/project.pbxproj
  Sennight/Sennight/ContentView.swift
  Sennight/Sennight/EntryView.swift
  Sennight/Sennight/Resources/Localization/Localizable.xcstrings
  Sennight/Sennight/ViewModels/UserViewModel.swift
  Sennight/Sennight/Views/Authentication/LoginView.swift
  Sennight/Sennight/Views/Authentication/SignUpView.swift
  Sennight/Sennight/Views/Dashboard/Cards/FactorsCardView.swift
  Sennight/Sennight/Views/MilestonePosts/MedalIcon.swift
  Sennight/Sennight/Views/MilestonePosts/MilestonePostCardView.swift
  Sennight/Sennight/Views/MilestonePosts/MilestonePostsView.swift
  Sennight/Sennight/Views/MilestonePosts/MyMilestonesView.swift
  Sennight/Sennight/Views/MilestonePosts/PostText.swift
  Sennight/Sennight/Views/MilestonePosts/SupportIcon.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep1View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep2View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep3View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingView.swift
  Sennight/Sennight/Views/Settings/SettingsView.swift
Labels: enhancement, swiftui

#28 Update models.py
  sennight-fastapi/app/models.py
Labels: enhancement, fastapi

#33 SEN-1 Update ER models
  sennight-fastapi/app/models.py
  sennight-fastapi/app/routes/users.py
  sennight-fastapi/app/schemas.py
  sennight-fastapi/app/schemas/__init__.py
  sennight-fastapi/app/schemas/activity.py
  sennight-fastapi/app/schemas/aid_product.py
  sennight-fastapi/app/schemas/health_benefit.py
  sennight-fastapi/app/schemas/milestone.py
  sennight-fastapi/app/schemas/milestone_post.py
  sennight-fastapi/app/schemas/motivation.py
  sennight-fastapi/app/schemas/quit_attempt.py
  sennight-fastapi/app/schemas/smoking_habit.py
  sennight-fastapi/app/schemas/smoking_log.py
  sennight-fastapi/app/schemas/symptom.py
  sennight-fastapi/app/schemas/trigger.py
  sennight-fastapi/app/schemas/user_schemas.py
Labels: enhancement, fastapi

#35 Adds mock user registration/login APIs
  sennight-fastapi/app/routes/mock_user.py
Labels: fastapi

#36 Update FastAPI server
  sennight-fastapi/app/models.py
  sennight-fastapi/app/routes/mock_user.py
  sennight-fastapi/app/routes/users.py
  sennight-fastapi/app/schemas.py
  sennight-fastapi/app/schemas/__init__.py
  sennight-fastapi/app/schemas/activity.py
  sennight-fastapi/app/schemas/aid_product.py
  sennight-fastapi/app/schemas/health_benefit.py
  sennight-fastapi/app/schemas/milestone.py
  sennight-fastapi/app/schemas/milestone_post.py
  sennight-fastapi/app/schemas/motivation.py
  sennight-fastapi/app/schemas/quit_attempt.py
  sennight-fastapi/app/schemas/smoking_habit.py
  sennight-fastapi/app/schemas/smoking_log.py
  sennight-fastapi/app/schemas/symptom.py
  sennight-fastapi/app/schemas/trigger.py
  sennight-fastapi/app/schemas/user_schemas.py
Labels: fastapi

#37 `rest-api-design-0.1.txt` 문서 생성
  docs/2024-07-07/rest-api-design-0.1.txt
Labels: documentation

#41 SEN-67/sykr1313/documentation
  docs/2024-07-02/er-diagram-v0.0.1.pdf
  docs/2024-07-02/logo-v0.0.0.png
  docs/2024-07-07/rest-api-design-v0.0.1.txt
  docs/2024-07-08/er-diagram-v0.0.2.png
  docs/2024-07-11/rest-api-design-v0.0.2.txt
  docs/2024-07-15/rest-api-design-v0.0.3.txt
Labels: documentation

#42 온보딩 스크린을 위한 와이어 프레임 추가
  Sennight/Sennight.xcodeproj/project.pbxproj
  Sennight/Sennight/Models/QuitAttempt.swift
  Sennight/Sennight/Models/SmokingHabit.swift
  Sennight/Sennight/Services/QuitAttemptService.swift
  Sennight/Sennight/Services/SmokingHabitService.swift
  Sennight/Sennight/ViewModels/QuitAttemptViewModel.swift
  Sennight/Sennight/ViewModels/SmokingHabitViewModel.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep4View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep5View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep6View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep7View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep8View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep9View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingView.swift
  Sennight/Sennight/Views/SplashScreenView.swift
Labels: enhancement, swiftui

#57 필요없는 주석 삭제
  Sennight/Sennight.xcodeproj/project.pbxproj
  Sennight/Sennight/ViewModels/SmokingHabitViewModel.swift
  Sennight/Sennight/ViewModels/User/LoginViewModel.swift
  Sennight/Sennight/ViewModels/User/SignUpViewModel.swift
  Sennight/Sennight/ViewModels/UserViewModel.swift
  Sennight/Sennight/Views/HelpersAndCustomViews/CustomTextFieldStyle.swift
Labels: swiftui, chore

#60 Update health progress card
  Sennight/Sennight.xcodeproj/project.pbxproj
  Sennight/Sennight/Models/HealthBenefit.swift
  Sennight/Sennight/Models/Milestone.swift
  Sennight/Sennight/Models/QuitAttempt.swift
  Sennight/Sennight/Models/Theme.swift
  Sennight/Sennight/Models/User.swift
  Sennight/Sennight/Resources/Assets.xcassets/Themes/mint.colorset/Contents.json
  Sennight/Sennight/Resources/Localization/Localizable.xcstrings
  Sennight/Sennight/Resources/Lottie Files/Constants.swift
  Sennight/Sennight/Resources/Lottie Files/Lavender fireworks.json
  Sennight/Sennight/Resources/Lottie Files/Poppy fireworks.json
  Sennight/Sennight/Resources/Lottie Files/Welcome confetti.json
  Sennight/Sennight/Resources/Lottie Files/Yellow fireworks.json
  Sennight/Sennight/Services/QuitAttemptService.swift
  Sennight/Sennight/Services/UserService.swift
  Sennight/Sennight/ViewModels/QuitAttemptViewModel.swift
  Sennight/Sennight/Views/Authentication/LoginView.swift
  Sennight/Sennight/Views/Authentication/SignUpView.swift
  Sennight/Sennight/Views/Dashboard/Cards/CircularGaugeView.swift
  Sennight/Sennight/Views/Dashboard/Cards/ElapsedTimeTextHeaderView.swift
  Sennight/Sennight/Views/Dashboard/Cards/HealthProgressCardView.swift
  Sennight/Sennight/Views/Dashboard/Cards/NewQuitAttemptSheet.swift
  Sennight/Sennight/Views/Dashboard/Cards/QuitAttemptCardView.swift
  Sennight/Sennight/Views/Dashboard/DashboardHeaderView.swift
  Sennight/Sennight/Views/Dashboard/DashboardView.swift
  Sennight/Sennight/Views/HelpersAndCustomViews/CircularGauge.swift
  Sennight/Sennight/Views/HelpersAndCustomViews/ElapsedTimeString.swift
  Sennight/Sennight/Views/HelpersAndCustomViews/StringToDateFormatter.swift
  Sennight/Sennight/Views/HomeView.swift
  Sennight/Sennight/Views/Onboarding/OnboardingStep1View.swift
  Sennight/Sennight/Views/Onboarding/OnboardingView.swift
Labels: enhancement, swiftui

#61 `Motivation`, `Trigger`, `Milestone`, `AidProduct`, `Symptom`, `Activity` enum 데이터 모델 추가
  Sennight/Sennight.xcodeproj/project.pbxproj
  Sennight/Sennight/Models/Activity.swift
  Sennight/Sennight/Models/AidProduct.swift
  Sennight/Sennight/Models/Milestone.swift
  Sennight/Sennight/Models/Motivation.swift
  Sennight/Sennight/Models/Symptom.swift
  Sennight/Sennight/Models/Trigger.swift
  Sennight/Sennight/Models/UserActivity.swift
  Sennight/Sennight/Models/UserAidProduct.swift
  Sennight/Sennight/Models/UserMilestone.swift
  Sennight/Sennight/Models/UserMotivation.swift
  Sennight/Sennight/Models/UserSymptom.swift
  Sennight/Sennight/Services/AidProductService.swift
  Sennight/Sennight/Services/FactorService.swift
  Sennight/Sennight/Services/MotivationService.swift
  Sennight/Sennight/ViewModels/AidProductViewModel.swift
  Sennight/Sennight/ViewModels/SmokingHabitViewModel.swift
  Sennight/Sennight/Views/Dashboard/Cards/AidProductDetailEditView.swift
  Sennight/Sennight/Views/Dashboard/Cards/AidProductRowView.swift
  Sennight/Sennight/Views/Dashboard/Cards/NewAidProductSheet.swift
  Sennight/Sennight/Views/Dashboard/Cards/UpdateAidProductSheet.swift
  Sennight/Sennight/Views/HomeView.swift
Labels: documentation, swiftui
